import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import AuthProvider from './context/AuthProvider'

import LayoutMain from '@/components/layout/LayoutMain';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <LayoutMain>
            {children}
          </LayoutMain>
        </AuthProvider>
      </body>
    </html>
  )
}
